[2023-10-01T02:36:14.342-0400] {processor.py:157} INFO - Started process (PID=18269) to work on /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:36:14.343-0400] {processor.py:829} INFO - Processing file /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-01T02:36:14.344-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:36:14.343-0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:36:14.350-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:36:14.348-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-01T02:36:14.350-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:36:14.350-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-01T02:36:14.350-0400] {processor.py:841} WARNING - No viable dags retrieved from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:36:14.364-0400] {processor.py:179} INFO - Processing /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-01T02:37:20.868-0400] {processor.py:157} INFO - Started process (PID=18353) to work on /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:37:20.887-0400] {processor.py:829} INFO - Processing file /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-01T02:37:20.888-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:37:20.887-0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:37:20.894-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:37:20.893-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-01T02:37:20.894-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:37:20.894-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-01T02:37:20.895-0400] {processor.py:841} WARNING - No viable dags retrieved from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:37:20.909-0400] {processor.py:179} INFO - Processing /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-10-01T02:38:21.991-0400] {processor.py:157} INFO - Started process (PID=18430) to work on /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:38:21.992-0400] {processor.py:829} INFO - Processing file /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-01T02:38:21.993-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:38:21.993-0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:38:21.999-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:38:21.998-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-01T02:38:21.999-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:38:21.999-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-01T02:38:22.000-0400] {processor.py:841} WARNING - No viable dags retrieved from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:38:22.014-0400] {processor.py:179} INFO - Processing /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-10-01T02:39:20.119-0400] {processor.py:157} INFO - Started process (PID=18649) to work on /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:39:20.120-0400] {processor.py:829} INFO - Processing file /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-01T02:39:20.121-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:39:20.120-0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:39:20.127-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:39:20.126-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-01T02:39:20.127-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:39:20.127-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-01T02:39:20.127-0400] {processor.py:841} WARNING - No viable dags retrieved from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:39:20.141-0400] {processor.py:179} INFO - Processing /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-01T02:40:24.434-0400] {processor.py:157} INFO - Started process (PID=18758) to work on /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:40:24.460-0400] {processor.py:829} INFO - Processing file /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-01T02:40:24.461-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:40:24.461-0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:40:24.467-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:40:24.466-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-01T02:40:24.467-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:40:24.467-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-01T02:40:24.467-0400] {processor.py:841} WARNING - No viable dags retrieved from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:40:24.481-0400] {processor.py:179} INFO - Processing /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2023-10-01T02:41:23.631-0400] {processor.py:157} INFO - Started process (PID=18874) to work on /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:41:23.632-0400] {processor.py:829} INFO - Processing file /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-01T02:41:23.634-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:41:23.633-0400] {dagbag.py:539} INFO - Filling up the DagBag from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:41:23.639-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:41:23.638-0400] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-01T02:41:23.640-0400] {logging_mixin.py:151} INFO - [2023-10-01T02:41:23.640-0400] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-01T02:41:23.640-0400] {processor.py:841} WARNING - No viable dags retrieved from /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-01T02:41:23.654-0400] {processor.py:179} INFO - Processing /home/erosennnin/anaconda3/envs/coursera/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
